Dev
Karnak19/WoW-Search-Engine pull request #16
Opened 2019-04-29 12:02 UTC by Zesysy

2019-04-30 10:51 UTC, Karnak19 commented on src/directory_home/Search-bar.jsx
> +// import errorPopover from "./errorPopover";
code mort

2019-04-30 10:51 UTC, Karnak19 commented on src/directory_home/Search-bar.jsx
> +        // if (inputValue === "") {
same here

2019-04-30 10:51 UTC, Karnak19 requested changes
remove dead code and go :)

2019-04-30 11:28 UTC, Zesysy commented on src/directory_home/Search-bar.jsx
> +        // if (inputValue === "") {
do to commit eb5f49e

2019-05-02 08:50 UTC, EnzoDuh commented
@Karnak19 Code's clean!

2019-05-02 09:33 UTC, Karnak19 approved these changes

2019-05-02 09:34 UTC, merged