Dev2
Karnak19/WoW-Search-Engine pull request #6
Opened 2019-04-09 07:22 UTC by Zesysy

To show at our Lead dev our beautiful job

2019-04-10 08:29 UTC, Karnak19 commented on wow-search-engine/public/index.html
> +/>
Qu'est-ce que ça fait là ça ?

2019-04-10 08:40 UTC, Karnak19 reviewed
Bon boulot dans l'ensemble, mais pourquoi le CSS de Bootstrap se trouve dans le Public ?

2019-04-10 08:47 UTC, EnzoDuh commented
C'est corrigé merci! @Karnak19

2019-04-10 09:52 UTC, Karnak19 commented
> C'est corrigé merci! @Karnak19

Pensez à push que je puisse voir, puis merge la PR :)

2019-04-10 09:57 UTC, Karnak19 requested changes
Pensez à push vos changements

2019-04-10 15:06 UTC, EnzoDuh commented
> Pensez à push vos changements

Done! @Karnak19

2019-04-12 07:18 UTC, Karnak19 approved these changes

2019-04-12 07:18 UTC, merged